# Generated by Django 2.1.1 on 2018-10-05 22:41

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250)),
                ('salary', models.IntegerField()),
                ('working_days', models.IntegerField()),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Joining Date')),
                ('Currency', models.CharField(choices=[('PKR', 'PKR'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=100)),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
