# Generated by Django 2.1.1 on 2018-10-05 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '3. Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Enter category such as Electronics, Furniture etc', max_length=250)),
            ],
            options={
                'verbose_name_plural': '1. Category',
            },
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Red', 'Red'), ('BLK', 'Black'), ('WHT', 'White'), ('GLD', 'Gold')], default='BLK', max_length=10)),
                ('condition', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Item-Details',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the mobile', max_length=1000)),
                ('Quantity', models.IntegerField()),
                ('Cost', models.IntegerField()),
                ('SellPrice', models.IntegerField()),
                ('Date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('In Stock', 'Available'), ('Out of Stock', 'Out of Stock'), ('On way', 'On way'), ('Reserved', 'Reserved')], default='In Stock', help_text='Availability', max_length=100)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.Brand')),
                ('category_name', models.ManyToManyField(help_text='Select a Category for this Item', to='Inventory.Category')),
            ],
            options={
                'verbose_name_plural': '4. Items',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Enter Type', max_length=100)),
            ],
            options={
                'verbose_name_plural': '2. Type',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='type_name',
            field=models.ManyToManyField(help_text='Select a Type for this Item', to='Inventory.Type'),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.Items'),
        ),
    ]
