# Generated by Django 2.1.1 on 2018-10-05 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('Employee', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderName', models.CharField(max_length=200)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Profile')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.EmployeeProfile')),
                ('Inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_category', to='Inventory.Items')),
            ],
        ),
    ]
